global:
  scrape_interval: 60s
  external_labels:
    monitor: 'prom'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['0.0.0.0:9090']
  - job_name: 'node-exporter' 
    scrape_interval: 30s
    static_configs: 
      - targets: ['node-exporter:9100']
  - job_name: 'co2-server'
    static_configs: 
      - targets: ['co2-server:5000']
